### ISSUE TITLE
Determine which scopes will need to be added to the callouts to the Spotify Web API

### ISSUE THREAD

**Issue by MattGrantUMich** [Goldify/Goldify#1]
These scopes can change over time. If that is the case, re-open the issue, edit the scope list, and request review once more

**Comment by MattGrantUMich** [comment]
Here's what the initial version of this project should require:

**Personalization**
`user-top-read`

**Playlists**
`playlist-modify-public` -> this should cover almost every permission we need from Spotify for playlists
`playlist-modify-private` -> the same permissions as above, except for private playlists (in case the user would like that)
`playlist-read-collaborative` -> this will allow the users to also take advantage of the Spotify collaborative playlists feature
`ugc-image-upload` -> this gives us permission to use a custom image for the playlist

**Comment by kyrod** [comment]
would we not need modify-collaborative instead if we wanted to try updating a collaborative playlist? but yeah these would be a good start, we can always add (or remove) as we add additional features

**Comment by MattGrantUMich** [comment]
Good point, for now let's stick with this list

**Personalization**
`user-top-read`

**Playlists**
`playlist-modify-public` -> this should cover almost every permission we need from Spotify for playlists
`playlist-modify-private` -> the same permissions as above, except for private playlists (in case the user would like that)
`ugc-image-upload` -> this gives us permission to use a custom image for the playlist

**Comment by MattGrantUMich** [comment]
We should also add the following:
`user-read-private user-read-email`

This will allow for the user data we se in the initial Spotify API commit

**Comment by MattGrantUMich** [comment]
Research complete.

Use this as a reference when adding in the components which require these scopes in the future.
