### ISSUE TITLE
Create Goldify logo

### ISSUE THREAD

**Issue by kyrod** [Goldify/Goldify#36]
**Is your feature request related to a problem? Please describe.**

We currently don't have a logo that satisfies Spotify's developer guidelines
**Describe the solution you'd like**

We should have a logo that can be displayed on our page, as well as be used for the cover image of the playlist
**Describe alternatives you've considered**

Continue using the gold spotify logo until we get our spotify api keys
**Additional context**

image should be at least 300x300, which is the minimum size for a playlist cover image

**Comment by MattGrantUMich** [comment]
Closed by commit by name of "Adds new goldify logo to assets folder"
